version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quantumtrades
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/quantumtrades?schema=public"
      JWT_SECRET: "dev-secret-change-me"
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: sh -c "npx prisma generate && npm run dev"
volumes:
  db-data:
